stages:
  - build

variables:
  DOCKER_REGISTRY: 302990163096.dkr.ecr.eu-west-1.amazonaws.com
  AWS_DEFAULT_REGION: eu-west-1
  APP_NAME: recommendationservice
  #### This is wrong: No need to write here in the future aws_acces_key_id and aws_secret_acess_key
  AWS_ACCESS_KEY_ID: AKIAUNC467SMNVURGBVP
  AWS_SECRET_ACCESS_KEY: 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

build:
  stage: build
  image: 
    name: docker:latest
  services:
    - docker:19-dind
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
  script:
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID .
    - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID
